// This file is autogenerated. Changes will be overwritten.
#include "6YEA5652QU/moc_Goen220GyroPlatformHost.cpp"
#include "6YEA5652QU/moc_MemsBoardStatus.cpp"
#include "6YEA5652QU/moc_MotorStatus.cpp"
#include "UVLADIE3JM/moc_Goen220GyroPlatformHostPrivate.cpp"
#include "WZBINUD2J3/moc_CommandFactory.cpp"
#include "66BJO7HFFQ/moc_Calculator.cpp"
#include "XASIB5EXNJ/moc_GyroPlatformDeviceCommunicator.cpp"
