#!/usr/bin/perl -w
# wrapdemo - демонстрация работы Text::Wrap

@input = ("Folding and splicing is the work of an editor,",
          "not a mere collection of silicon",
          "and",
          "mobile electrons!");

use Text::Wrap qw($columns &wrap);
$columns = 20;
print "0123456789" x 2, "\n";
print wrap("    ", "  ", @input), "\n";

#результат выгл€дит так:

01234567890123456789
    Folding and

  splicing is the
  work of an
  editor, not a
  mere collection
  of silicon and
  mobile electrons!
