[General]
IRCam.IR_Cam_BytesPerPixel=0
IRCam.IR_Cam_Device=/dev/video11
IRCam.IR_Cam_Height=512
IRCam.IR_Cam_Timeout=15000
IRCam.IR_Cam_Width=640
IRCam.IR_UART_Baudrate=0
IRCam.IR_UART_Device=/dev/ttyS8
IRCam.IR_ExpPeriod=92600
#192500
#IRCam.IR_Exp=40000
IRCam.IR_Exp=40000
IRCam.IR_GPOL=820.000
IRLens.UART_Baudrate=19200
IRLens.UART_Device=/dev/ttyS0
LDC20I.UART_Baudrate=115200
LDC20I.UART_Device=/dev/ttyS7
Network.IP_Edge2=192.168.1.93
Network.IP_HostPC=192.168.1.105
Network.UDP_Port_Edge2=52515
Network.UDP_Port_HostPC=52516
TVCam.TV_Cam_BytesPerPixel=0
TVCam.TV_Cam_Device=/dev/video0
TVCam.TV_Cam_Height=1080
TVCam.TV_Cam_Timeout=15000
TVCam.TV_Cam_Width=1920
TVCam.TV_UART_Baudrate=115200
TVCam.TV_UART_Device=/dev/ttyS9
