/* soapMessengerServiceSoapBindingProxy.h
   Generated by gSOAP 2.8.74 for duplo.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapMessengerServiceSoapBindingProxy_H
#define soapMessengerServiceSoapBindingProxy_H
#include "soapH.h"

    class SOAP_CMAC MessengerServiceSoapBindingProxy {
      public:
        /// Context to manage proxy IO and data
        struct soap *soap;
        /// flag indicating that this context is owned by this proxy and should be deleted by the destructor
        bool soap_own;
        /// Endpoint URL of service 'MessengerServiceSoapBindingProxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in duplo.h, if any
        /// Construct a proxy with new managing context
        MessengerServiceSoapBindingProxy();
        /// Copy constructor
        MessengerServiceSoapBindingProxy(const MessengerServiceSoapBindingProxy& rhs);
        /// Construct proxy given a shared managing context
        MessengerServiceSoapBindingProxy(struct soap*);
        /// Construct proxy given a shared managing context and endpoint URL
        MessengerServiceSoapBindingProxy(struct soap*, const char *soap_endpoint_url);
        /// Constructor taking an endpoint URL
        MessengerServiceSoapBindingProxy(const char *soap_endpoint_url);
        /// Constructor taking input and output mode flags for the new managing context
        MessengerServiceSoapBindingProxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        MessengerServiceSoapBindingProxy(const char *soap_endpoint_url, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        MessengerServiceSoapBindingProxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes non-shared managing context only (use destroy() to delete deserialized data)
        virtual ~MessengerServiceSoapBindingProxy();
        /// Initializer used by constructors
        virtual void MessengerServiceSoapBindingProxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual MessengerServiceSoapBindingProxy *copy();
        /// Copy assignment
        MessengerServiceSoapBindingProxy& operator=(const MessengerServiceSoapBindingProxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault subcode QName string (NULL when absent)
        virtual const char *soap_fault_subcode();
        /// Get SOAP Fault string/reason (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail XML string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        /// Web service operation 'process' to the default endpoint with the default SOAP Action header, returns SOAP_OK or error code
        virtual int process(ns1__process *ns1__process_, ns1__processResponse &ns1__processResponse_) { return this->process(NULL, NULL, ns1__process_, ns1__processResponse_); }
        /// Web service operation 'process' to an endpoint with a SOAP Action header, returns SOAP_OK or error code
        virtual int process(const char *soap_endpoint_url, const char *soap_action, ns1__process *ns1__process_, ns1__processResponse &ns1__processResponse_);
        /// Web service operation 'processGetInfo' to the default endpoint with the default SOAP Action header, returns SOAP_OK or error code
        virtual int processGetInfo(ns1__processGetInfo *ns1__processGetInfo_, ns1__processGetInfoResponse &ns1__processGetInfoResponse_) { return this->processGetInfo(NULL, NULL, ns1__processGetInfo_, ns1__processGetInfoResponse_); }
        /// Web service operation 'processGetInfo' to an endpoint with a SOAP Action header, returns SOAP_OK or error code
        virtual int processGetInfo(const char *soap_endpoint_url, const char *soap_action, ns1__processGetInfo *ns1__processGetInfo_, ns1__processGetInfoResponse &ns1__processGetInfoResponse_);
        /// Web service operation 'getVersion' to the default endpoint with the default SOAP Action header, returns SOAP_OK or error code
        virtual int getVersion(ns1__getVersion *ns1__getVersion_, ns1__getVersionResponse &ns1__getVersionResponse_) { return this->getVersion(NULL, NULL, ns1__getVersion_, ns1__getVersionResponse_); }
        /// Web service operation 'getVersion' to an endpoint with a SOAP Action header, returns SOAP_OK or error code
        virtual int getVersion(const char *soap_endpoint_url, const char *soap_action, ns1__getVersion *ns1__getVersion_, ns1__getVersionResponse &ns1__getVersionResponse_);
    };
#endif
