#ifndef OWLET_GLOBAL_DEFINES_H
#define OWLET_GLOBAL_DEFINES_H

#define OWLET_CHANNEL_ID_TVRGB        (0x00u)
#define OWLET_CHANNEL_ID_FUSION       (0x04u)
#define OWLET_CHANNEL_ID_MWIR         (0x01u)
#define OWLET_CHANNEL_ID_TVGRAY       (0x03u)
#define OWLET_CHANNEL_ID_TVGRAYMWIR   (0x02u)
#define OWLET_CHANNEL_ID_TEST         (0x07u)

#endif // GLOBAL_DEFINES_H
