# Install script for directory: /home/jhon/Sublime_tests/6_BOOST_development_cookbook

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Debug")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Install shared libraries without execute permission?
if(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  set(CMAKE_INSTALL_SO_NO_EXE "0")
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

# Set default install directory permissions.
if(NOT DEFINED CMAKE_OBJDUMP)
  set(CMAKE_OBJDUMP "/usr/bin/objdump")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/01_02_any/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/01_03_variant/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/01_04_A_any_db_example/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/01_04_B_variant_db_example/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/01_05_optional/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/01_06_array/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/01_07_A_tuple/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/01_07_B_tuple_construction_order/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/01_08_bind/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/01_09_type_index/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/01_10_A_move/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/01_11_noncopyable/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/01_12_A_noncopyable_movable/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/01_13_algorithm/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/02_01_scoped_ptr/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/02_03_scoped_array/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/02_05_function_fobject/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/02_06_function_fpointer/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/02_07_function_lambda_c++11/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/02_08_ptr_container_c++11/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/02_09_scope_exit/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/02_10_base_from_member/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/03_01_lexical_to_number/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/03_02_lexical_to_string/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/03_03_numeric_cast/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/03_04_lexical_user_defined/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/03_05_polymorphic_cast/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/03_06_spirit/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/03_07_spirit_rules/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/04_01_conditional/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/04_02_disable_if_c/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/04_03_enable_if_c/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/04_04_is_stdvector/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/04_05_mpl_int_/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/04_06_static_assert/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/04_07_typeof/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/05_01_atomics/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/05_02_interruptions/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/05_03_mutex/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/05_04_shared_lock/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/05_05_thread/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/05_06_thread_group/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/05_07_thread_specific_ptr/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/05_08_work_queue/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/06_01_tasks_processor_base/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/06_02_tasks_processor_timers/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/06_03_tasks_processor_network/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/06_04_tasks_processor_multithread/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/06_05_conveyor/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/06_06_nonblocking_barrier/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/06_07_exception_ptr/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/06_08_tasks_processor_signals/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/07_01_case_conv/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/07_02_regex_match/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/07_03_regex_replace/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/07_04_format/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/07_05_string_algo/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/07_06_iterator_range/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/07_07_string_ref/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/08_01_vector_of_types/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/08_02_manipulating_vector_of_types/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/08_03_result_of_c++11/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/08_04_higher_order_metafunctions/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/08_05_lazy/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/08_06_tuple_to_string/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/08_07_splitting_tuple/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/09_01_hash/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/09_02_unordered/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/09_03_bimap/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/09_04_multiindex/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/09_05_slist_and_pool/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/09_06_flat/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/10_01_int128/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/10_02_no_rtti/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/10_03_extern_template/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/10_04_constexpr_c++11/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/10_05_noexcept_c++11/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/10_06_export_import/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/10_07_my_library/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/10_08_version/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/11_01_listing_files/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/11_02_erasing_files/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/11_03_interprocess_basics/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/11_04_interprocess_queue/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/11_05_interprocess_pointers/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/11_06_reading_files/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/11_07_coroutines/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/12_01_graph/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/12_02_graph_vis/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/12_03_random/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/12_04_math/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/12_05_testing/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/12_06_testing_advanced/cmake_install.cmake")
  include("/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/12_07_gil/cmake_install.cmake")

endif()

if(CMAKE_INSTALL_COMPONENT)
  set(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
else()
  set(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
endif()

string(REPLACE ";" "\n" CMAKE_INSTALL_MANIFEST_CONTENT
       "${CMAKE_INSTALL_MANIFEST_FILES}")
file(WRITE "/home/jhon/Sublime_tests/6_BOOST_development_cookbook/build-cmake/${CMAKE_INSTALL_MANIFEST}"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
